DROP TABLE IF EXISTS version;
CREATE TABLE IF NOT EXISTS version (
	version INT NOT NULL DEFAULT 0,
	PRIMARY KEY (version)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO version VALUES(1);
